import QtQuick
import QtQuick.Shapes

Item {
  id: root
  clip: true

  // generated by Graph::updateQmlData()
  property var qmlData: []

  Repeater {
    model: root.qmlData

    // One delegate per curve — holds the shared style properties.
    delegate: Item {
      id: curveDelegate

      // .segments is List<QPolygonF>: a main QPolygonF split at discontinuities
      // the next Repeater handles that
      required property var modelData

      anchors.fill: parent

      Repeater {
        model: curveDelegate.modelData.segments

        Shape {
          required property var modelData  // QPolygonF for this segment

          anchors.fill: parent
          preferredRendererType: Shape.CurveRenderer

          ShapePath {
            readonly property var style: curveDelegate.modelData.style

            strokeColor:  style.color
            strokeWidth:  style.lineWidth
            fillColor:  "transparent"
            capStyle:   ShapePath.RoundCap
            joinStyle:  ShapePath.RoundJoin
            strokeStyle:  style.dashPattern.length > 0
                    ? ShapePath.DashLine
                    : ShapePath.SolidLine
            dashPattern:  style.dashPattern

            PathPolyline {
              path: modelData
            }
          }
        }
      }
    }
  }
}
