name: linux build & bundle
on:
  workflow_dispatch:

jobs:
  build-bundle:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.*'

      - name: Install Dependencies
        run: |
          sudo apt install libboost-all-dev python3-pip libfuse2 libxcb-cursor0
          pip3 install --user meson ninja

      - name: Build & Bundle
        run: ./deploy/linux-bundle-appimage.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: deploy/ZeGrapher*AppImage
