name: macOS build & bundle
on:
  workflow_dispatch:

jobs:
  build-bundle:
    runs-on: macos-15-intel
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          brew install boost coreutils qtbase qtsvg qtdeclarative qttools qttranslations meson

      - name: Select correct Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build & Bundle
        run: ./deploy/macos-bundle-dmg.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v5
        with:
          name: macos-artifact
          path: deploy/ZeGrapher*dmg
