name: macOS build & bundle
on:
  workflow_dispatch:

jobs:
  build-bundle:
    runs-on: macos-13
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.*'

      - name: Install Dependencies
        run: |
          brew install boost coreutils
          pip3 install meson ninja

      - name: Select correct Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build & Bundle
        run: ./deploy/macos-bundle-dmg.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: deploy/ZeGrapher*dmg
