name: Windows build & bundle

on:
  workflow_call:
    inputs:
      msystem:
        required: true
        type: string

jobs:
  build-bundle:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ inputs.msystem }}
          update: true
          install: git pactoys

      - name: Build & Bundle
        run: |
          echo 'Running in MSYS2!'
          ./deploy/windows-bundle-7z.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v5
        with:
          name: windows-artifact-${{ inputs.msystem }}
          path: deploy/ZeGrapher*.exe
